# Generated by Django 3.1.5 on 2021-01-23 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('local', models.CharField(max_length=255)),
                ('t_a', models.FloatField(blank=True)),
                ('t_t', models.FloatField(blank=True)),
                ('umd', models.FloatField(blank=True)),
                ('n_g', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(default=0)),
                ('on_off', models.BooleanField(default=0)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.environment')),
            ],
        ),
        migrations.CreateModel(
            name='AirConditioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.FloatField(default=0)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('on_off', models.BooleanField(default=0)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.environment')),
            ],
        ),
    ]
