# Generated by Django 3.1.5 on 2021-01-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='n_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='t_a',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='t_t',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='umd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
